### PR TITLE
fixing the issue when comment in the comment section, the file cart goes back to the previous state.

### PR DESCRIPTION
**Pull request by wfy1997**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### CODE REVIEW

**Comment by AjayDoddapaneni** [comment]
Looks like we are using a lot of local storage can we clear the unnecessary local storage on component destroy.

**Comment by wfy1997** [comment]
I think all these local-storage variables are pretty important, I do not think we can delete any of them.

**Comment by AjayDoddapaneni** [comment]
I was saying once we navigate to a different page we can clear some local storage right?

**Comment by wfy1997** [comment]
Yes, that is correct.

**Review by AjayDoddapaneni — APPROVED** [review]

**Pull request merged**
