### PR TITLE
BENTO-2453 Check for API data in Query Bar

### PR DESCRIPTION
**Pull request by amattu2**
## Description

Introduces a fix to filter selected facets with no data from appearing in the active filters query bar.

> **Note**: This will require a new release for `@bento-core/query-bar`

Fixes # [BENTO-2453](https://tracker.nci.nih.gov/browse/BENTO-2453)

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

N/A

### CODE REVIEW

**Comment by iksheth** [comment]
> ## Description
> Introduces a fix to filter selected facets with no data from appearing in the active filters query bar.
> 
> > Note: This will require a new release for `@bento-core/query-bar`
> 
> Fixes # [BENTO-2453](https://tracker.nci.nih.gov/browse/BENTO-2453)
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [x]  Bug fix (non-breaking change which fixes an issue)
> 
> ## How Has This Been Tested?
> N/A

I believe we will need to release a patch for the "@bento-core/query-bar" component.

**Comment by iksheth** [comment]
@amattu2 do we need any update in Documentation?

**Review by iksheth — APPROVED** [review]
LGTM 👍🏻

**Review by iksheth — APPROVED** [review]
LGTM 👍🏻

**Comment by amattu2** [comment]
> @amattu2 do we need any update in Documentation?

Documentation updated

**Pull request merged**
