### PR TITLE
Dashboard select button

### PR DESCRIPTION
**Pull request by AjayDoddapaneni**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
## How Has This Been Tested?

### CODE REVIEW

**Review by iksheth — APPROVED** [review]
LGTM 👍🏻

**Comment by skiran86** [comment]
@AjayDoddapaneni Looks like this PR generated conflicts due to the recent merge. Take a look

**Comment by AjayDoddapaneni** [comment]
@skiran86 Fixed

**Review by iksheth — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
