### PR TITLE
BENTO-2229 Implement Refactored Widget & Chart components

### PR DESCRIPTION
**Pull request by amattu2**
## Description

This task addresses [BENTO-2229](https://tracker.nci.nih.gov/browse/BENTO-2229) and [BENTO-2227](https://tracker.nci.nih.gov/browse/BENTO-2227), which implements refactored Widget, DonutChart, and SunburstChart components created in [BENTO-2228](https://tracker.nci.nih.gov/browse/BENTO-2229). Both of these tickets belong to [BENTO-2226](https://tracker.nci.nih.gov/browse/BENTO-2226).

Fixes # (issue)

- [BENTO-2229](https://tracker.nci.nih.gov/browse/BENTO-2229)
- [BENTO-2227](https://tracker.nci.nih.gov/browse/BENTO-2227)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This change was tested by comparing the production deployment of bento against the local changes on the Explore, Arm, and Program view pages to ensure there were no differences between the two. The local deployment used the refactored components, and the production deployment did not.

### CODE REVIEW

**Comment by amattu2** [comment]
Pending approval from [BENTO-2227](https://tracker.nci.nih.gov/browse/BENTO-2227).

**Review by iksheth — APPROVED** [review]
LGTM 👍🏻

**Review by rana22 — APPROVED** [review]
LGTM

**Review by iksheth — APPROVED** [review]
Looks Good to me 👍🏻

**Pull request merged**
